(()=>{
const STATUS={
'Especialización en IA Avanzada para Roles Emergentes':{type:'active',label:'Activa hasta',date:'20 sep 2026'},
'Inteligencia Artificial Generativa Aplicada a la Educación':{type:'expired',label:'Expiró',date:'1 abr 2026'},
'Máster en Ciencia de Datos e Inteligencia Artificial':{type:'expired',label:'Expiró',date:'2 mar 2026'},
'Máster Universitario en Computación y Sistemas Inteligentes':{type:'expired',label:'Expiró',date:'2 mar 2026'},
'Transformación Digital con IA y Automatización':{type:'active',label:'Activa',date:'Sin fecha de cierre informada'},
'Chevening Scholarship 2027–2028':{type:'active',label:'Activa hasta',date:'6 oct 2026'},
'Becas Monbukagakusho (MEXT)':{type:'upcoming',label:'Se activa en',date:'abril 2027 (estimado)'},
'Global Korea Scholarship – Graduate (GKS-G)':{type:'expired',label:'Expiró',date:'25 feb 2026'},
'Beca del Gobierno Chino – Programa Bilateral':{type:'expired',label:'Expiró',date:'28 feb 2026'},
'Türkiye Scholarships':{type:'expired',label:'Expiró',date:'20 feb 2026'},
'Singapore International Graduate Award (SINGA)':{type:'upcoming',label:'Se activa en',date:'próxima convocatoria 2027'}
};
try{if(typeof META!=='undefined'&&META['Chile']){META['Chile'].img='assets/chile-fixed.jpg?rev=202609140050';if(typeof render==='function')render()}}catch(e){}
function injectStyle(){if(document.getElementById('catalogStatusStyle'))return;const s=document.createElement('style');s.id='catalogStatusStyle';s.textContent=`
.statusMeta{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 11px}.statusTag,.dateTag{display:inline-flex;align-items:center;gap:6px;min-height:28px;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:800;line-height:1}.statusTag:before{content:'';width:7px;height:7px;border-radius:50%;background:currentColor}.statusTag.active{color:#13875c;background:#eafaf3}.statusTag.expired{color:#b42318;background:#fff0ee}.statusTag.upcoming{color:#6d5dfc;background:#f1efff}.dateTag{color:#56677e;background:#f5f8fb}.card.isExpired .apply{background:#eef2f6;color:#667085;box-shadow:none}.card.isExpired{background:#fcfcfd}
@media(max-width:700px){
html,body{width:100%;max-width:100%;overflow-x:hidden}.top{height:62px;padding:0 16px;grid-template-columns:minmax(0,1fr) auto}.brand{font-size:18px;gap:9px}.logo{width:34px;height:34px;border-radius:10px}.brand small{font-size:5.5px;letter-spacing:1.2px}.tools{gap:0}.headsearch,.iconbtn,nav{display:none!important}.profile{height:36px;padding:0 15px;font-size:12px}.page{padding:18px 16px 42px}.hero{display:block;min-height:0}.hero h1{font-size:38px;line-height:1.02;letter-spacing:-2.4px;margin:9px 0 12px}.hero p{font-size:15px;line-height:1.45}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px}.stat{display:block}.statIcon{width:32px;height:32px;font-size:13px;margin-bottom:6px}.stat strong{font-size:20px}.stat small{font-size:8px}.photoArea{display:none}
.filters{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:20px 0 14px}.filters input{grid-column:1/-1;height:46px}.filters select{height:46px;min-width:0;padding-left:12px;padding-right:34px;background-position:right 12px center}.filters select:nth-of-type(3){grid-column:1/2}.go{grid-column:2/3;height:46px;border-radius:13px}.workspace{display:grid!important;grid-template-columns:1fr!important;gap:16px}.workspace>div:first-child{display:flex;flex-direction:column;min-width:0}.chips{order:0;display:flex;gap:8px;overflow-x:auto;scrollbar-width:none;margin:0 0 10px;padding:0 0 4px}.chips::-webkit-scrollbar{display:none}.chip{flex:0 0 auto;padding:9px 13px;font-size:11px}
.mapCard{order:1;height:300px!important;border-radius:18px;margin:0;overflow:hidden;background:linear-gradient(180deg,#fbfdff,#f6faff)}.mapImgWrap{position:absolute!important;inset:10px 14px 22px!important;display:flex!important;align-items:center!important;justify-content:center!important}.mapImg{display:block!important;width:100%!important;height:100%!important;object-fit:contain!important;opacity:.95!important;filter:sepia(0) saturate(.45) hue-rotate(165deg) brightness(1.45) contrast(.78)!important;mix-blend-mode:multiply!important}.mapDots{display:block!important;opacity:.55!important}.routes{display:block}.marker{font-size:8px;padding:6px 7px;max-width:120px;overflow:hidden;text-overflow:ellipsis}.marker:before{width:8px;height:8px;margin-right:5px}.marker.chile{font-size:9px;padding:7px 8px}.marker.chile:before{width:10px;height:10px}.mapControls{right:9px;bottom:9px;gap:6px}.mapControls button{width:34px;height:34px;border-radius:10px;font-size:16px}
.side{order:2;position:static!important;width:100%;min-height:0;margin:0;border-radius:18px;overflow:hidden}.cover{height:auto!important;aspect-ratio:575/298;background:#eef3f8}.cover img{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important}.cover img[alt='Chile']{object-position:center center!important}.cover:has(img[alt='Chile']) .coverFlag,.cover:has(img[alt='Chile']) .coverTitle{display:none!important}.cover:after{background:linear-gradient(180deg,transparent 62%,rgba(2,20,44,.18))}.sideBody{padding:15px}.sideBody h3{font-size:15px;margin:0 0 8px}.sch{grid-template-columns:34px minmax(0,1fr) auto;gap:8px;padding:10px 0}.flagBox{width:34px;height:34px}.sch strong{font-size:12px;line-height:1.25}.sch small{font-size:9px}.lang{font-size:9px;padding:5px 7px}
.destinations{order:3;margin-top:18px}.destinations h3{font-size:18px;margin-bottom:10px}.destRow{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.dest{height:112px;border-radius:15px}.dest img{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important}.dest img[alt='Chile']{object-position:center center!important}.dest:has(img[alt='Chile']) span{display:none!important}.dest:has(img[alt='Chile']):after{display:none!important}.dest span{left:11px;bottom:10px}.dest b{font-size:13px}.dest small{font-size:10px}
.catalog{margin-top:30px}.catalogHead{display:block}.catalogHead h2{font-size:22px;line-height:1.16;margin:4px 0}.catalogHead #countText{display:block;font-size:11px;color:#74839a}.grid{grid-template-columns:1fr!important;gap:12px;margin-top:12px}.card{padding:16px;border-radius:16px}.card h3{font-size:17px;line-height:1.24}.card p{font-size:12px;line-height:1.45}.apply{width:100%;text-align:center;padding:11px 13px}
}
`;document.head.appendChild(s)}
function decorate(){injectStyle();document.querySelectorAll('.card').forEach(card=>{if(card.querySelector('.statusMeta'))return;const title=card.querySelector('h3')?.textContent?.trim();const st=STATUS[title];if(!st)return;const box=document.createElement('div');box.className='statusMeta';box.innerHTML=`<span class="statusTag ${st.type}">${st.label}</span><span class="dateTag">${st.date}</span>`;const badge=card.querySelector('.badge');if(badge)badge.insertAdjacentElement('afterend',box);else card.prepend(box);if(st.type==='expired')card.classList.add('isExpired')})}
function boot(){decorate();const grid=document.getElementById('grid');if(grid)new MutationObserver(decorate).observe(grid,{childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();