const state={scholarships:[],favorites:new Set(JSON.parse(localStorage.getItem('becas100:favorites')||'[]')),favoritesOnly:false,map:null,markers:[],selectedCountry:null,panelStatus:''};
const $=s=>document.querySelector(s);
const normalize=v=>(v||'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const uniq=a=>[...new Set(a.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));
const statusLabel={open:'Abierta',upcoming:'Próximamente',closed:'Cerrada'};
const countryMeta={
  'Chile':{lat:-33.45,lng:-70.67,flag:'🇨🇱'},
  'España':{lat:40.42,lng:-3.70,flag:'🇪🇸'},
  'México':{lat:19.43,lng:-99.13,flag:'🇲🇽'},
  'Colombia':{lat:4.71,lng:-74.07,flag:'🇨🇴'},
  'Argentina':{lat:-34.60,lng:-58.38,flag:'🇦🇷'},
  'Perú':{lat:-12.05,lng:-77.04,flag:'🇵🇪'},
  'Estados Unidos':{lat:38.90,lng:-77.04,flag:'🇺🇸'},
  'Canadá':{lat:45.42,lng:-75.70,flag:'🇨🇦'},
  'Alemania':{lat:52.52,lng:13.40,flag:'🇩🇪'},
  'Reino Unido':{lat:51.50,lng:-0.12,flag:'🇬🇧'},
  'Francia':{lat:48.86,lng:2.35,flag:'🇫🇷'},
  'Italia':{lat:41.90,lng:12.50,flag:'🇮🇹'},
  'Japón':{lat:35.68,lng:139.69,flag:'🇯🇵'},
  'Australia':{lat:-35.28,lng:149.13,flag:'🇦🇺'}
};
function primaryCountry(raw){return (raw||'').split('/')[0].trim()}
function setOptions(id,values){const el=$(id);values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)})}
function saveFavorites(){localStorage.setItem('becas100:favorites',JSON.stringify([...state.favorites]));$('#favoriteCount').textContent=state.favorites.size}
function renderStats(){const v=state.scholarships.filter(x=>x.verified100);$('#statVerified').textContent=v.length;$('#statOpen').textContent=v.filter(x=>x.status==='open').length;$('#statCountries').textContent=uniq(v.map(x=>primaryCountry(x.country))).length;const dates=v.map(x=>x.lastChecked).filter(Boolean).sort();$('#lastUpdated').textContent=dates.length?`Última revisión: ${new Date(dates.at(-1)+'T12:00:00').toLocaleDateString('es-CL')}`:'Sin fecha de revisión'}
function getFilters(){return{q:normalize($('#searchInput').value),category:$('#categoryFilter').value,country:$('#countryFilter').value,mode:$('#modeFilter').value,level:$('#levelFilter').value,status:$('#statusFilter').value}}
function filtered(){const f=getFilters();let list=state.scholarships.filter(x=>x.verified100);list=list.filter(x=>!f.q||normalize([x.title,x.institution,x.country,x.category,x.summary].join(' ')).includes(f.q));if(f.category)list=list.filter(x=>x.category===f.category);if(f.country)list=list.filter(x=>primaryCountry(x.country)===f.country);if(f.mode)list=list.filter(x=>x.mode===f.mode);if(f.level)list=list.filter(x=>x.level===f.level);if(f.status)list=list.filter(x=>x.status===f.status);if(state.favoritesOnly)list=list.filter(x=>state.favorites.has(x.id));return list}
function renderCards(){const list=filtered().sort((a,b)=>({open:0,upcoming:1,closed:2}[a.status]-({open:0,upcoming:1,closed:2}[b.status])||String(a.deadline||'9999').localeCompare(String(b.deadline||'9999')));$('#resultsCount').textContent=`${list.length} beca${list.length===1?'':'s'}`;const grid=$('#scholarshipGrid');grid.innerHTML='';if(!list.length){grid.innerHTML='<div class="empty">No hay becas que coincidan con estos filtros.</div>';return}const t=$('#cardTemplate');list.forEach(x=>{const n=t.content.cloneNode(true);n.querySelector('.category').textContent=x.category;n.querySelector('h3').textContent=x.title;n.querySelector('.institution').textContent=x.institution;const meta=n.querySelector('.meta');[primaryCountry(x.country),x.mode,x.level,x.language].filter(Boolean).forEach(m=>{const s=document.createElement('span');s.textContent=m;meta.appendChild(s)});n.querySelector('.summary').textContent=x.summary;n.querySelector('.coverage').textContent=`✓ ${x.coverage}`;const st=n.querySelector('.status');st.textContent=statusLabel[x.status]||x.status;st.classList.add(x.status);n.querySelector('.apply').href=x.url;const fav=n.querySelector('.favorite');if(state.favorites.has(x.id)){fav.classList.add('active');fav.textContent='♥'}fav.onclick=()=>{state.favorites.has(x.id)?state.favorites.delete(x.id):state.favorites.add(x.id);saveFavorites();renderAll()};grid.appendChild(n)})}
function groupByCountry(list){const g={};list.forEach(x=>{const c=primaryCountry(x.country);(g[c]||(g[c]=[])).push(x)});return g}
function renderDestinations(){const groups=groupByCountry(filtered());const row=$('#destinationRow');row.innerHTML='';Object.entries(groups).sort((a,b)=>b[1].length-a[1].length).forEach(([country,items])=>{const m=countryMeta[country]||{flag:'🌍'};const el=document.createElement('button');el.className='destination';el.innerHTML=`<span class="flag">${m.flag}</span><strong>${country}</strong><span>${items.length} beca${items.length===1?'':'s'}</span>`;el.onclick=()=>selectCountry(country);row.appendChild(el)})}
function initMap(){state.map=L.map('worldMap',{zoomControl:true,worldCopyJump:true,minZoom:2,maxZoom:7,attributionControl:true}).setView([15,0],2);L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{subdomains:'abcd',maxZoom:19,attribution:'&copy; OpenStreetMap &copy; CARTO'}).addTo(state.map);setTimeout(()=>state.map.invalidateSize(),200)}
function renderMap(){if(!state.map)return;state.markers.forEach(m=>state.map.removeLayer(m));state.markers=[];const groups=groupByCountry(filtered());Object.entries(groups).forEach(([country,items])=>{const meta=countryMeta[country];if(!meta)return;const hasOpen=items.some(x=>x.status==='open');const icon=L.divIcon({className:'marker-wrap',html:`<div class="scholar-marker ${hasOpen?'':'closed-only'}"><div class="marker-label">${meta.flag} ${country}<small>${items.length} beca${items.length===1?'':'s'}</small></div></div>`,iconSize:[22,22],iconAnchor:[11,11]});const marker=L.marker([meta.lat,meta.lng],{icon}).addTo(state.map);marker.on('click',()=>selectCountry(country));state.markers.push(marker)});if(!Object.keys(groups).length)return;const coords=Object.keys(groups).map(c=>countryMeta[c]).filter(Boolean).map(m=>[m.lat,m.lng]);if(coords.length===1)state.map.flyTo(coords[0],4,{duration:.8});else if(coords.length>1)state.map.fitBounds(coords,{padding:[70,70],maxZoom:3})}
function selectCountry(country){state.selectedCountry=country;const meta=countryMeta[country]||{flag:'🌍'};$('#panelFlag').textContent=meta.flag;$('#panelCountry').textContent=country;state.panelStatus='';document.querySelectorAll('[data-panel-status]').forEach(b=>b.classList.toggle('active',b.dataset.panelStatus===''));renderPanel();$('#panelEmpty').hidden=true;$('#panelContent').hidden=false;$('#countryPanel').classList.add('open');if(state.map&&meta.lat!=null)state.map.flyTo([meta.lat,meta.lng],Math.max(state.map.getZoom(),4),{duration:1})}
function renderPanel(){if(!state.selectedCountry)return;let items=filtered().filter(x=>primaryCountry(x.country)===state.selectedCountry);if(state.panelStatus)items=items.filter(x=>x.status===state.panelStatus);$('#panelCount').textContent=`${items.length} beca${items.length===1?'':'s'}`;const list=$('#panelList');list.innerHTML='';if(!items.length){list.innerHTML='<div class="empty" style="padding:24px">Sin resultados con este filtro.</div>';return}items.forEach(x=>{const el=document.createElement('article');el.className='panel-item';el.innerHTML=`<div class="mini-top"><h4>${x.title}</h4><span class="mini-status ${x.status==='closed'?'closed':''}">${statusLabel[x.status]||x.status}</span></div><p>${x.institution}</p><div class="mini-meta">${x.level} · ${x.mode}<br>${x.coverage}</div><a href="${x.url}" target="_blank" rel="noopener noreferrer">Postular ↗</a>`;list.appendChild(el)})}
function renderAll(){renderCards();renderDestinations();renderMap();if(state.selectedCountry)renderPanel()}
async function init(){const sch=await fetch('data/scholarships.json?v=map1').then(r=>r.json());state.scholarships=sch.scholarships||[];setOptions('#categoryFilter',uniq(state.scholarships.map(x=>x.category)));setOptions('#countryFilter',uniq(state.scholarships.map(x=>primaryCountry(x.country))));setOptions('#modeFilter',uniq(state.scholarships.map(x=>x.mode)));setOptions('#levelFilter',uniq(state.scholarships.map(x=>x.level)));initMap();['searchInput','categoryFilter','countryFilter','modeFilter','levelFilter','statusFilter'].forEach(id=>$('#'+id).addEventListener('input',renderAll));$('#clearFilters').onclick=()=>{['searchInput','categoryFilter','countryFilter','modeFilter','levelFilter','statusFilter'].forEach(id=>$('#'+id).value='');state.favoritesOnly=false;renderAll()};$('#favoritesButton').onclick=()=>{state.favoritesOnly=!state.favoritesOnly;$('#favoritesButton').classList.toggle('active',state.favoritesOnly);renderAll()};$('#closePanel').onclick=()=>$('#countryPanel').classList.remove('open');document.querySelectorAll('[data-panel-status]').forEach(btn=>btn.onclick=()=>{state.panelStatus=btn.dataset.panelStatus;document.querySelectorAll('[data-panel-status]').forEach(b=>b.classList.toggle('active',b===btn));renderPanel()});saveFavorites();renderStats();renderAll()}
init().catch(err=>{console.error(err);$('#scholarshipGrid').innerHTML='<div class="empty">No pudimos cargar la plataforma. Intenta recargar.</div>'});