const state={scholarships:[],favorites:new Set(),favoritesOnly:false,selectedCountry:null,panelType:'',map:{scale:1,tx:0,ty:0,drag:false,x:0,y:0},projection:null,mapReady:false};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const normalize=v=>(v||'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const uniq=a=>[...new Set(a.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));
const statusLabel={open:'Abierta',upcoming:'Próxima',closed:'Histórica'};
const countryMeta={
 'Chile':{flag:'🇨🇱',lat:-33.45,lng:-70.67,iso:152,color:'#ff43c8'},'España':{flag:'🇪🇸',lat:40.42,lng:-3.70,iso:724,color:'#31f59a'},'México':{flag:'🇲🇽',lat:19.43,lng:-99.13,iso:484,color:'#ff43c8'},'Colombia':{flag:'🇨🇴',lat:4.71,lng:-74.07,iso:170,color:'#ff43c8'},'Argentina':{flag:'🇦🇷',lat:-34.60,lng:-58.38,iso:32,color:'#ff43c8'},'Perú':{flag:'🇵🇪',lat:-12.05,lng:-77.04,iso:604,color:'#ff43c8'},'Estados Unidos':{flag:'🇺🇸',lat:38.90,lng:-77.04,iso:840,color:'#178cff'},'Canadá':{flag:'🇨🇦',lat:45.42,lng:-75.70,iso:124,color:'#178cff'},'Alemania':{flag:'🇩🇪',lat:52.52,lng:13.40,iso:276,color:'#31f59a'},'Reino Unido':{flag:'🇬🇧',lat:51.50,lng:-0.12,iso:826,color:'#31f59a'},'Francia':{flag:'🇫🇷',lat:48.86,lng:2.35,iso:250,color:'#31f59a'},'Italia':{flag:'🇮🇹',lat:41.90,lng:12.50,iso:380,color:'#31f59a'},'Japón':{flag:'🇯🇵',lat:35.68,lng:139.69,iso:392,color:'#ffb12b'},'Australia':{flag:'🇦🇺',lat:-35.28,lng:149.13,iso:36,color:'#8f5cff'},'China':{flag:'🇨🇳',lat:39.90,lng:116.40,iso:156,color:'#ffb12b'},'Corea del Sur':{flag:'🇰🇷',lat:37.57,lng:126.98,iso:410,color:'#9f5cff'},'Turquía':{flag:'🇹🇷',lat:39.93,lng:32.86,iso:792,color:'#ff7a33'},'Singapur':{flag:'🇸🇬',lat:1.35,lng:103.82,iso:702,color:'#25dcff'}
};
function primaryCountry(raw){return(raw||'').split('/')[0].trim()}
function languageTokens(raw){return uniq((raw||'').split(/\s*[\/,+;]\s*/).map(x=>x.trim()).filter(Boolean))}
function safeJSON(text,fallback){try{return JSON.parse(text)}catch{return fallback}}
function loadLocalState(){state.favorites=new Set(safeJSON(localStorage.getItem('becas100:favorites')||'[]',[]));const p=safeJSON(localStorage.getItem('becas100:profile')||'{}',{});if(p.name)$('#profileButton').textContent=p.name}
function saveFavorites(){localStorage.setItem('becas100:favorites',JSON.stringify([...state.favorites]));$('#favoriteCount').textContent=state.favorites.size}
function setOptions(id,values){const el=$(id);values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)})}
function baseVerified(){return state.scholarships.filter(x=>x&&x.verified100===true&&(x.eligibleChile===true||x.eligibleLatam===true))}
function animateNumber(el,to){const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce){el.textContent=to;return}const start=performance.now(),dur=550;function tick(now){const p=Math.min(1,(now-start)/dur);el.textContent=Math.round(to*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}
function renderStats(){const v=baseVerified(),countries=uniq(v.map(x=>primaryCountry(x.country)));animateNumber($('#statVerified'),v.length);animateNumber($('#statCountries'),countries.length);animateNumber($('#footerVerified'),v.length);animateNumber($('#footerCountries'),countries.length);const dates=v.map(x=>x.lastChecked).filter(Boolean).sort();$('#lastUpdated').textContent=dates.length?`Revisión ${new Date(dates.at(-1)+'T12:00:00').toLocaleDateString('es-CL')}`:'Actualización diaria'}
function renderFilteredStats(){const v=filtered(),countries=uniq(v.map(x=>primaryCountry(x.country)));$('#statVerified').textContent=v.length;$('#statCountries').textContent=countries.length;$('#footerVerified').textContent=v.length;$('#footerCountries').textContent=countries.length}
function getFilters(){return{q:normalize($('#searchInput').value),category:$('#categoryFilter').value,country:$('#countryFilter').value,mode:$('#modeFilter').value,language:$('#languageFilter').value,level:$('#levelFilter').value,status:$('#statusFilter').value}}
function filtered(){const f=getFilters();let list=baseVerified();if(f.q)list=list.filter(x=>normalize([x.title,x.institution,x.country,x.category,x.summary,x.language,x.eligibilityLabel].join(' ')).includes(f.q));if(f.category)list=list.filter(x=>x.category===f.category);if(f.country)list=list.filter(x=>primaryCountry(x.country)===f.country);if(f.mode)list=list.filter(x=>x.mode===f.mode);if(f.language)list=list.filter(x=>languageTokens(x.language).includes(f.language));if(f.level)list=list.filter(x=>x.level===f.level);if(f.status)list=list.filter(x=>x.status===f.status);if(state.favoritesOnly)list=list.filter(x=>state.favorites.has(x.id));return list}
function groupByCountry(list){const g={};for(const x of list){const c=primaryCountry(x.country);(g[c]||(g[c]=[])).push(x)}return g}
function renderCards(){const order={open:0,upcoming:1,closed:2};const list=filtered().sort((a,b)=>(order[a.status]??9)-(order[b.status]??9)||String(a.deadline||'9999').localeCompare(String(b.deadline||'9999')));$('#resultsCount').textContent=`${list.length} beca${list.length===1?'':'s'}`;const grid=$('#scholarshipGrid');grid.innerHTML='';if(!list.length){grid.innerHTML='<div class="empty">No hay becas que coincidan con estos filtros.</div>';return}const t=$('#cardTemplate');for(const x of list){const n=t.content.cloneNode(true);n.querySelector('.category').textContent=x.category;n.querySelector('h3').textContent=x.title;n.querySelector('.institution').textContent=x.institution;const meta=n.querySelector('.meta');[primaryCountry(x.country),x.mode,x.level,x.language,x.eligibilityLabel].filter(Boolean).forEach(m=>{const s=document.createElement('span');s.textContent=m;meta.appendChild(s)});n.querySelector('.summary').textContent=x.summary;n.querySelector('.coverage').textContent=`✓ ${x.coverage}`;const st=n.querySelector('.status');st.textContent=statusLabel[x.status]||x.status;st.classList.add(x.status);n.querySelector('.apply').href=x.url;const fav=n.querySelector('.favorite');if(state.favorites.has(x.id)){fav.classList.add('active');fav.textContent='♥'}fav.onclick=()=>{state.favorites.has(x.id)?state.favorites.delete(x.id):state.favorites.add(x.id);saveFavorites();renderAll()};grid.appendChild(n)}}
function renderDestinations(){const groups=groupByCountry(filtered()),row=$('#destinationRow');row.innerHTML='';const entries=Object.entries(groups).sort((a,b)=>b[1].length-a[1].length);if(!entries.length){row.innerHTML='<div class="empty compact">No hay destinos con estos filtros.</div>';return}for(const [country,items] of entries){const m=countryMeta[country]||{flag:'🌍',color:'#20d9ff'};const el=document.createElement('button');el.className='destination';el.style.setProperty('--country-color',m.color);el.innerHTML=`<div class="destination-visual"><span>${m.flag}</span><i></i></div><div class="destination-copy"><strong>${country}</strong><small>${items.length} beca${items.length===1?'':'s'}</small></div><b>→</b>`;el.onclick=()=>selectCountry(country);row.appendChild(el)}}
function fallbackProject(lat,lng){return[(lng+180)/360*1000,(90-lat)/180*520]}
function projectCountry(country){const m=countryMeta[country];if(!m)return[500,260];return state.projection?state.projection([m.lng,m.lat]):fallbackProject(m.lat,m.lng)}
function regionColor(feature){if(!window.d3||!state.projection)return'#17304b';const c=d3.geoCentroid(feature),lon=c[0],lat=c[1];if(lon<-30)return lat<5?'#522451':'#123e73';if(lon>115)return lat<0?'#382d68':'#5b3d14';if(lon>30)return lat<5?'#4b2818':'#4a3c18';return lat<15?'#4e2c1f':'#123f37'}
function drawFallbackMap(){const svg=$('#worldSvg');svg.innerHTML=`<g class="fallback-land"><path d="M76 118L142 78 211 87 254 129 225 171 192 219 141 210 98 174 70 145Z"/><path d="M205 227L253 246 282 290 266 340 242 384 222 432 199 384 183 326 178 280Z"/><path d="M408 112L462 83 527 91 575 119 628 105 703 106 758 120 823 116 865 139 834 172 777 184 728 176 682 207 616 202 574 181 521 168 468 149Z"/><path d="M466 199L520 192 563 215 586 254 571 310 541 357 517 405 485 384 458 330 447 274Z"/><path d="M838 343L899 329 943 351 936 393 897 412 853 395 825 366Z"/><path d="M819 214L844 210 860 225 849 247 829 242Z"/></g>`;$('#mapError').hidden=false;state.projection=null;state.mapReady=true;$('#mapLoading').hidden=true}
async function drawWorld(){const svgEl=$('#worldSvg');if(!window.d3||!window.topojson){drawFallbackMap();return}try{const world=await d3.json('https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json');const countries=topojson.feature(world,world.objects.countries).features;const projection=d3.geoNaturalEarth1().fitExtent([[22,20],[978,500]],{type:'Sphere'});state.projection=projection;const path=d3.geoPath(projection),svg=d3.select(svgEl);svg.selectAll('*').remove();svg.append('path').datum({type:'Sphere'}).attr('class','ocean-sphere').attr('d',path);svg.append('g').attr('class','country-layer').selectAll('path').data(countries).join('path').attr('class',d=>`country-shape ${Object.values(countryMeta).some(m=>String(m.iso)===String(d.id))?'known-country':''}`).attr('d',path).attr('fill',d=>regionColor(d)).attr('data-id',d=>d.id).on('click',(event,d)=>{const pair=Object.entries(countryMeta).find(([,m])=>String(m.iso)===String(d.id));if(pair&&groupByCountry(filtered())[pair[0]])selectCountry(pair[0])});state.mapReady=true;$('#mapLoading').hidden=true;$('#mapError').hidden=true}catch(e){console.warn('Fallback de mapa:',e);drawFallbackMap()}}
function renderParticles(){const layer=$('#particles');if(layer.childElementCount)return;const colors=['#1ccfff','#25f1a6','#ff4fd8','#ffb12b','#8f5cff'];for(let i=0;i<85;i++){const p=document.createElement('i');p.style.left=`${4+Math.random()*92}%`;p.style.top=`${9+Math.random()*78}%`;p.style.setProperty('--c',colors[i%colors.length]);p.style.animationDelay=`-${Math.random()*8}s`;p.style.animationDuration=`${6+Math.random()*8}s`;layer.appendChild(p)}}
function applyMapTransform(){const w=$('#mapWorld');w.style.transform=`translate3d(${state.map.tx}px,${state.map.ty}px,0) scale(${state.map.scale})`}
function zoomMap(delta){state.map.scale=Math.max(1,Math.min(2.5,state.map.scale+delta));if(state.map.scale===1){state.map.tx=0;state.map.ty=0}applyMapTransform()}
function resetMap(){state.map={...state.map,scale:1,tx:0,ty:0,drag:false};applyMapTransform()}
function centerOnCountry(country){const [x,y]=projectCountry(country),stage=$('#mapStage').getBoundingClientRect(),scale=1.45;state.map.scale=scale;state.map.tx=stage.width/2-(x/1000*stage.width)*scale;state.map.ty=stage.height/2-(y/520*stage.height)*scale;applyMapTransform()}
function drawRoute(country){const svg=$('#routeSvg');svg.innerHTML='';if(!country)return;const from=country==='Chile'?(groupByCountry(filtered())['España']?'España':null):'Chile';if(!from||!countryMeta[from]||!countryMeta[country])return;const [x1,y1]=projectCountry(from),[x2,y2]=projectCountry(country),cx=(x1+x2)/2,cy=Math.min(y1,y2)-95;svg.innerHTML=`<path class="travel-path" d="M${x1},${y1} Q${cx},${cy} ${x2},${y2}"/><circle class="travel-plane" cx="${x1}" cy="${y1}" r="4"><animateMotion dur="3.4s" repeatCount="indefinite" path="M0,0 Q${cx-x1},${cy-y1} ${x2-x1},${y2-y1}"/></circle>`}
function renderMap(){const groups=groupByCountry(filtered()),layer=$('#markerLayer');layer.innerHTML='';Object.entries(groups).forEach(([country,items],index)=>{const m=countryMeta[country];if(!m)return;const [x,y]=projectCountry(country),hasOpen=items.some(x=>x.status==='open'),marker=document.createElement('button');marker.className=`map-marker ${hasOpen?'has-open':'closed-only'}`;marker.style.left=`${x/10}%`;marker.style.top=`${y/5.2}%`;marker.style.setProperty('--marker-color',m.color);marker.style.animationDelay=`${index*100}ms`;marker.innerHTML=`<span class="marker-core"><i></i></span><span class="marker-card"><b>${m.flag} ${country}</b><small>${items.length} beca${items.length===1?'':'s'}</small><em>›</em></span>`;marker.onclick=e=>{e.stopPropagation();selectCountry(country)};layer.appendChild(marker)});if(state.selectedCountry&&!groups[state.selectedCountry])closePanel();drawRoute(state.selectedCountry)}
function typeMatches(item,type){if(!type)return true;const s=normalize(item.level);if(type==='master')return s.includes('master')||s.includes('magister');if(type==='doctorado')return s.includes('doctor');if(type==='curso')return s.includes('curso')||s.includes('especializacion')||s.includes('diplom');return true}
function renderPanel(){if(!state.selectedCountry)return;let items=filtered().filter(x=>primaryCountry(x.country)===state.selectedCountry).filter(x=>typeMatches(x,state.panelType));$('#panelCount').textContent=`${items.length} beca${items.length===1?'':'s'} disponibles`;const list=$('#panelList');list.innerHTML='';if(!items.length){list.innerHTML='<div class="empty compact">No hay resultados en esta categoría.</div>';return}for(const x of items){const el=document.createElement('article');el.className='panel-item';const deadline=x.deadline?new Date(x.deadline+'T12:00:00').toLocaleDateString('es-CL'):'Sin fecha publicada';el.innerHTML=`<div class="panel-item-main"><button class="panel-fav" aria-label="Guardar">${state.favorites.has(x.id)?'♥':'♡'}</button><h4>${x.title}</h4><p>${x.institution}</p><div class="panel-meta"><span class="coverage-mini">◆ ${x.coverage}</span><span>${x.level} · ${x.mode} · ${x.language}</span><span>Elegibilidad: ${x.eligibilityLabel||'Chile / Latinoamérica'}</span><span>Cierre: ${deadline}</span></div><div class="panel-actions"><span class="mini-status ${x.status}">${statusLabel[x.status]||x.status}</span><a href="${x.url}" target="_blank" rel="noopener noreferrer">Postular ↗</a></div></div>`;el.querySelector('.panel-fav').onclick=()=>{state.favorites.has(x.id)?state.favorites.delete(x.id):state.favorites.add(x.id);saveFavorites();renderAll()};list.appendChild(el)}}
function selectCountry(country){const m=countryMeta[country];if(!m)return;state.selectedCountry=country;state.panelType='';$('#panelFlag').textContent=m.flag;$('#panelCountry').textContent=country;$('#countryCover').style.setProperty('--cover-color',m.color);$$('[data-panel-type]').forEach(b=>b.classList.toggle('active',!b.dataset.panelType));$('#panelEmpty').hidden=true;$('#panelContent').hidden=false;$('#countryPanel').classList.add('open');renderPanel();drawRoute(country);centerOnCountry(country)}
function closePanel(){$('#countryPanel').classList.remove('open');state.selectedCountry=null;$('#panelContent').hidden=true;$('#panelEmpty').hidden=false;drawRoute(null);resetMap()}
function renderAll(){renderFilteredStats();renderCards();renderDestinations();renderMap();if(state.selectedCountry)renderPanel()}
function populateFilters(){setOptions('#categoryFilter',uniq(baseVerified().map(x=>x.category)));setOptions('#countryFilter',uniq(baseVerified().map(x=>primaryCountry(x.country))));setOptions('#modeFilter',uniq(baseVerified().map(x=>x.mode)));setOptions('#languageFilter',uniq(baseVerified().flatMap(x=>languageTokens(x.language))));setOptions('#levelFilter',uniq(baseVerified().map(x=>x.level)))}
function wireUI(){const ids=['searchInput','categoryFilter','countryFilter','modeFilter','languageFilter','levelFilter','statusFilter'];ids.forEach(id=>$('#'+id).addEventListener('input',renderAll));$('#applyFilters').onclick=renderAll;$('#clearFilters').onclick=()=>{ids.forEach(id=>$('#'+id).value='');$('#topSearch').value='';state.favoritesOnly=false;$$('[data-quick-status]').forEach(b=>b.classList.toggle('active',b.dataset.quickStatus===''));renderAll();resetMap()};$('#topSearch').addEventListener('input',e=>{$('#searchInput').value=e.target.value;renderAll()});$('#searchInput').addEventListener('input',e=>{$('#topSearch').value=e.target.value});$$('[data-quick-status]').forEach(btn=>btn.onclick=()=>{$('#statusFilter').value=btn.dataset.quickStatus;$$('[data-quick-status]').forEach(b=>b.classList.toggle('active',b===btn));renderAll()});$('#favoritesButton').onclick=()=>{state.favoritesOnly=!state.favoritesOnly;$('#favoritesButton').classList.toggle('active',state.favoritesOnly);renderAll()};$('#closePanel').onclick=closePanel;$$('[data-panel-type]').forEach(btn=>btn.onclick=()=>{state.panelType=btn.dataset.panelType;$$('[data-panel-type]').forEach(b=>b.classList.toggle('active',b===btn));renderPanel()});$('#panelAll').onclick=()=>{if(state.selectedCountry){$('#countryFilter').value=state.selectedCountry;renderAll();$('#becas').scrollIntoView({behavior:'smooth'})}};$('#zoomIn').onclick=()=>zoomMap(.18);$('#zoomOut').onclick=()=>zoomMap(-.18);$('#resetMap').onclick=resetMap;const stage=$('#mapStage'),world=$('#mapWorld');stage.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;state.map.drag=true;state.map.x=e.clientX;state.map.y=e.clientY;world.classList.add('dragging');stage.setPointerCapture?.(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!state.map.drag||state.map.scale<=1)return;state.map.tx+=e.clientX-state.map.x;state.map.ty+=e.clientY-state.map.y;state.map.x=e.clientX;state.map.y=e.clientY;applyMapTransform()});['pointerup','pointercancel','pointerleave'].forEach(ev=>stage.addEventListener(ev,()=>{state.map.drag=false;world.classList.remove('dragging')}));stage.addEventListener('wheel',e=>{e.preventDefault();zoomMap(e.deltaY<0?.15:-.15)},{passive:false});$('#themeButton').onclick=()=>document.body.classList.toggle('low-glow');$('#profileButton').onclick=()=>$('#profileDialog').showModal();$('#saveProfile').onclick=()=>{const name=$('#profileName').value.trim();localStorage.setItem('becas100:profile',JSON.stringify({name,country:$('#profileCountry').value}));if(name)$('#profileButton').textContent=name};$('#mobileFilters').onclick=()=>$('#filtersPanel').classList.toggle('mobile-open')}
async function loadScholarships(){const url=new URL('./data/scholarships.json',window.location.href);url.searchParams.set('v',Date.now());const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`scholarships.json respondió ${r.status}`);const data=await r.json();if(!Array.isArray(data.scholarships))throw new Error('Formato scholarships.json inválido');state.scholarships=data.scholarships;return state.scholarships}
async function init(){loadLocalState();wireUI();try{await loadScholarships();populateFilters();renderStats();renderAll();saveFavorites();renderParticles();await drawWorld();renderMap();const groups=groupByCountry(baseVerified());const initial=groups['España']?'España':Object.keys(groups)[0];if(initial)selectCountry(initial)}catch(err){console.error(err);$('#resultsCount').textContent='Error de carga';$('#scholarshipGrid').innerHTML=`<div class="empty error"><strong>No pudimos cargar las becas.</strong><span>${err.message}</span><button onclick="location.reload()">Reintentar</button></div>`;$('#statVerified').textContent='!';$('#statCountries').textContent='!';$('#footerVerified').textContent='!';$('#footerCountries').textContent='!';$('#lastUpdated').textContent='Error al cargar datos';drawFallbackMap()}}
init();
