const state={scholarships:[],favorites:new Set(JSON.parse(localStorage.getItem('becas100:favorites')||'[]')),favoritesOnly:false,selectedCountry:null,panelStatus:'',map:{scale:1,tx:0,ty:0,drag:false,x:0,y:0}};
const $=s=>document.querySelector(s);
const normalize=v=>(v||'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const uniq=a=>[...new Set(a.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));
const statusLabel={open:'Abierta',upcoming:'Próximamente',closed:'Histórica'};
const countryMeta={
  'Chile':{flag:'🇨🇱',x:27,y:70,color:'#ff4fd8'},'España':{flag:'🇪🇸',x:50,y:31,color:'#50ff87'},'México':{flag:'🇲🇽',x:19,y:48,color:'#ff4fd8'},'Colombia':{flag:'🇨🇴',x:25,y:60,color:'#ff4fd8'},'Argentina':{flag:'🇦🇷',x:29,y:78,color:'#ff4fd8'},'Perú':{flag:'🇵🇪',x:24,y:67,color:'#ff4fd8'},'Estados Unidos':{flag:'🇺🇸',x:20,y:35,color:'#208cff'},'Canadá':{flag:'🇨🇦',x:20,y:23,color:'#208cff'},'Alemania':{flag:'🇩🇪',x:53,y:28,color:'#50ff87'},'Reino Unido':{flag:'🇬🇧',x:48,y:25,color:'#50ff87'},'Francia':{flag:'🇫🇷',x:49,y:31,color:'#50ff87'},'Italia':{flag:'🇮🇹',x:53,y:35,color:'#50ff87'},'Japón':{flag:'🇯🇵',x:84,y:39,color:'#ffb228'},'Australia':{flag:'🇦🇺',x:82,y:71,color:'#9f5cff'}
};
function primaryCountry(raw){return(raw||'').split('/')[0].trim()}
function setOptions(id,values){const el=$(id);values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)})}
function saveFavorites(){localStorage.setItem('becas100:favorites',JSON.stringify([...state.favorites]));$('#favoriteCount').textContent=state.favorites.size}
function baseVerified(){return state.scholarships.filter(x=>x.verified100)}
function renderStats(){const v=baseVerified();const countries=uniq(v.map(x=>primaryCountry(x.country)));$('#statVerified').textContent=v.length;$('#statCountries').textContent=countries.length;$('#footerVerified').textContent=v.length;$('#footerCountries').textContent=countries.length;const dates=v.map(x=>x.lastChecked).filter(Boolean).sort();$('#lastUpdated').textContent=dates.length?`Revisión ${new Date(dates.at(-1)+'T12:00:00').toLocaleDateString('es-CL')}`:'Actualización diaria'}
function getFilters(){return{q:normalize($('#searchInput').value),category:$('#categoryFilter').value,country:$('#countryFilter').value,mode:$('#modeFilter').value,level:$('#levelFilter').value,status:$('#statusFilter').value}}
function filtered(){const f=getFilters();let list=baseVerified();list=list.filter(x=>!f.q||normalize([x.title,x.institution,x.country,x.category,x.summary].join(' ')).includes(f.q));if(f.category)list=list.filter(x=>x.category===f.category);if(f.country)list=list.filter(x=>primaryCountry(x.country)===f.country);if(f.mode)list=list.filter(x=>x.mode===f.mode);if(f.level)list=list.filter(x=>x.level===f.level);if(f.status)list=list.filter(x=>x.status===f.status);if(state.favoritesOnly)list=list.filter(x=>state.favorites.has(x.id));return list}
function groupByCountry(list){const g={};list.forEach(x=>{const c=primaryCountry(x.country);(g[c]||(g[c]=[])).push(x)});return g}
function renderCards(){const list=filtered().sort((a,b)=>({open:0,upcoming:1,closed:2}[a.status]-({open:0,upcoming:1,closed:2}[b.status])||String(a.deadline||'9999').localeCompare(String(b.deadline||'9999')));$('#resultsCount').textContent=`${list.length} beca${list.length===1?'':'s'}`;const grid=$('#scholarshipGrid');grid.innerHTML='';if(!list.length){grid.innerHTML='<div class="empty">No hay becas que coincidan con estos filtros.</div>';return}const t=$('#cardTemplate');list.forEach(x=>{const n=t.content.cloneNode(true);n.querySelector('.category').textContent=x.category;n.querySelector('h3').textContent=x.title;n.querySelector('.institution').textContent=x.institution;const meta=n.querySelector('.meta');[primaryCountry(x.country),x.mode,x.level,x.language].filter(Boolean).forEach(m=>{const s=document.createElement('span');s.textContent=m;meta.appendChild(s)});n.querySelector('.summary').textContent=x.summary;n.querySelector('.coverage').textContent=`✓ ${x.coverage}`;const st=n.querySelector('.status');st.textContent=statusLabel[x.status]||x.status;st.classList.add(x.status);n.querySelector('.apply').href=x.url;const fav=n.querySelector('.favorite');if(state.favorites.has(x.id)){fav.classList.add('active');fav.textContent='♥'}fav.onclick=()=>{state.favorites.has(x.id)?state.favorites.delete(x.id):state.favorites.add(x.id);saveFavorites();renderAll()};grid.appendChild(n)})}
function renderDestinations(){const groups=groupByCountry(filtered());const row=$('#destinationRow');row.innerHTML='';Object.entries(groups).sort((a,b)=>b[1].length-a[1].length).forEach(([country,items])=>{const m=countryMeta[country]||{flag:'🌍',color:'#25dcff'};const el=document.createElement('button');el.className='destination';el.style.setProperty('--dest-glow',m.color);el.innerHTML=`<span class="flag">${m.flag}</span><strong>${country}</strong><span>${items.length} beca${items.length===1?'':'s'}</span><b>→</b>`;el.onclick=()=>selectCountry(country);row.appendChild(el)})}
function applyMapTransform(){const world=$('#mapWorld');world.style.transform=`translate(${state.map.tx}px,${state.map.ty}px) scale(${state.map.scale})`}
function zoomMap(delta){state.map.scale=Math.max(1,Math.min(2.45,state.map.scale+delta));if(state.map.scale===1){state.map.tx=0;state.map.ty=0}applyMapTransform()}
function resetMap(){state.map={...state.map,scale:1,tx:0,ty:0,drag:false};applyMapTransform()}
function centerOnCountry(country){const m=countryMeta[country];if(!m)return;const stage=$('#mapStage').getBoundingClientRect();const scale=1.45;state.map.scale=scale;state.map.tx=stage.width/2-(m.x/100*stage.width)*scale;state.map.ty=stage.height/2-(m.y/100*stage.height)*scale;applyMapTransform()}
function renderMap(){const groups=groupByCountry(filtered());const layer=$('#markerLayer');layer.innerHTML='';Object.entries(groups).forEach(([country,items],index)=>{const m=countryMeta[country];if(!m)return;const hasOpen=items.some(x=>x.status==='open');const marker=document.createElement('button');marker.className=`map-marker ${hasOpen?'has-open':'closed-only'} ${country==='Chile'?'is-chile':''}`;marker.style.left=`${m.x}%`;marker.style.top=`${m.y}%`;marker.style.animationDelay=`${index*120}ms`;marker.innerHTML=`<span class="marker-core"></span><span class="marker-card"><b>${m.flag} ${country}</b><small>${items.length} beca${items.length===1?'':'s'}</small></span>`;marker.onclick=e=>{e.stopPropagation();selectCountry(country)};layer.appendChild(marker)});const both=groups['Chile']&&groups['España'];$('#travelArc').style.display=both?'':'none';$('#travelDot').style.display=both?'':'none'}
function selectCountry(country){state.selectedCountry=country;const m=countryMeta[country]||{flag:'🌍',color:'#25dcff'};$('#panelFlag').textContent=m.flag;$('#panelCountry').textContent=country;$('#countryCover').style.background=`radial-gradient(circle at 75% 25%,${m.color}99,transparent 22%),linear-gradient(135deg,#173153,#41265f 58%,${m.color}88)`;state.panelStatus='';document.querySelectorAll('[data-panel-status]').forEach(b=>b.classList.toggle('active',b.dataset.panelStatus===''));$('#panelEmpty').hidden=true;$('#panelContent').hidden=false;$('#countryPanel').classList.add('open');renderPanel();centerOnCountry(country)}
function renderPanel(){if(!state.selectedCountry)return;let items=filtered().filter(x=>primaryCountry(x.country)===state.selectedCountry);if(state.panelStatus)items=items.filter(x=>x.status===state.panelStatus);$('#panelCount').textContent=`${items.length} beca${items.length===1?'':'s'} disponibles`;const list=$('#panelList');list.innerHTML='';if(!items.length){list.innerHTML='<div class="empty" style="padding:24px">Sin resultados con este filtro.</div>';return}items.forEach(x=>{const el=document.createElement('article');el.className='panel-item';el.innerHTML=`<div class="mini-top"><h4>${x.title}</h4><span class="mini-status ${x.status}">${statusLabel[x.status]||x.status}</span></div><p>${x.institution}</p><div class="mini-meta">✓ ${x.coverage}<br>${x.level} · ${x.mode}</div><a href="${x.url}" target="_blank" rel="noopener noreferrer">Postular ↗</a>`;list.appendChild(el)})}
function renderAll(){renderCards();renderDestinations();renderMap();if(state.selectedCountry)renderPanel()}
function syncSearch(source,target){target.value=source.value;renderAll()}
function wireMap(){const stage=$('#mapStage'),world=$('#mapWorld');stage.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;state.map.drag=true;state.map.x=e.clientX;state.map.y=e.clientY;world.classList.add('dragging');stage.setPointerCapture?.(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!state.map.drag||state.map.scale<=1)return;state.map.tx+=e.clientX-state.map.x;state.map.ty+=e.clientY-state.map.y;state.map.x=e.clientX;state.map.y=e.clientY;applyMapTransform()});['pointerup','pointercancel','pointerleave'].forEach(ev=>stage.addEventListener(ev,()=>{state.map.drag=false;world.classList.remove('dragging')}));stage.addEventListener('wheel',e=>{e.preventDefault();zoomMap(e.deltaY<0?.16:-.16)},{passive:false});$('#zoomIn').onclick=()=>zoomMap(.18);$('#zoomOut').onclick=()=>zoomMap(-.18);$('#resetMap').onclick=resetMap}
async function init(){const sch=await fetch(`data/scholarships.json?v=${Date.now()}`).then(r=>{if(!r.ok)throw new Error('No se pudo cargar scholarships.json');return r.json()});state.scholarships=sch.scholarships||[];setOptions('#categoryFilter',uniq(state.scholarships.map(x=>x.category)));setOptions('#countryFilter',uniq(state.scholarships.map(x=>primaryCountry(x.country))));setOptions('#modeFilter',uniq(state.scholarships.map(x=>x.mode)));setOptions('#levelFilter',uniq(state.scholarships.map(x=>x.level)));
  const liveIds=['searchInput','categoryFilter','countryFilter','modeFilter','levelFilter','statusFilter'];liveIds.forEach(id=>$('#'+id).addEventListener('input',renderAll));$('#applyFilters').onclick=renderAll;$('#clearFilters').onclick=()=>{liveIds.forEach(id=>$('#'+id).value='');$('#topSearch').value='';state.favoritesOnly=false;document.querySelectorAll('[data-quick-status]').forEach(b=>b.classList.toggle('active',b.dataset.quickStatus===''));renderAll();resetMap()};$('#favoritesButton').onclick=()=>{state.favoritesOnly=!state.favoritesOnly;$('#favoritesButton').classList.toggle('active',state.favoritesOnly);renderAll()};$('#topSearch').addEventListener('input',e=>syncSearch(e.target,$('#searchInput')));$('#searchInput').addEventListener('input',e=>{$('#topSearch').value=e.target.value});document.querySelectorAll('[data-quick-status]').forEach(btn=>btn.onclick=()=>{$('#statusFilter').value=btn.dataset.quickStatus;document.querySelectorAll('[data-quick-status]').forEach(b=>b.classList.toggle('active',b===btn));renderAll()});$('#closePanel').onclick=()=>$('#countryPanel').classList.remove('open');document.querySelectorAll('[data-panel-status]').forEach(btn=>btn.onclick=()=>{state.panelStatus=btn.dataset.panelStatus;document.querySelectorAll('[data-panel-status]').forEach(b=>b.classList.toggle('active',b===btn));renderPanel()});$('#panelAll').onclick=()=>{if(state.selectedCountry){$('#countryFilter').value=state.selectedCountry;renderAll();document.querySelector('#becas').scrollIntoView({behavior:'smooth'});$('#countryPanel').classList.remove('open')}};wireMap();const img=$('#worldImage');img.onerror=()=>{if(!img.dataset.fallback){img.dataset.fallback='1';img.src='https://cdn.jsdelivr.net/gh/melenaos/Menelabs.VectorAtlas@main/dist/world.svg'}};saveFavorites();renderStats();renderAll();resetMap()}
init().catch(err=>{console.error(err);$('#scholarshipGrid').innerHTML='<div class="empty">No pudimos cargar la plataforma. Recarga la página.</div>'});